# Generated by Django 3.2.4 on 2021-08-15 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20210717_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(help_text='Feed ID', primary_key=True, serialize=False)),
                ('title', models.TextField(help_text='Feed title')),
                ('content', models.TextField(blank=True, help_text='Feed Content', null=True)),
            ],
        ),
    ]
