# Generated by Django 3.2.4 on 2021-08-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_auto_20210815_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(help_text='Feed ID', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(help_text='User Id')),
                ('title', models.TextField(help_text='Feed title')),
                ('content', models.TextField(blank=True, help_text='Feed Content', null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
