# Generated by Django 3.2.4 on 2021-08-15 01:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_auto_20210815_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='create_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
