# Generated by Django 3.2.4 on 2021-08-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_auto_20210815_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
