# Generated by Django 3.2.4 on 2021-08-16 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_alter_feed_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='user_id',
            field=models.IntegerField(default=1, help_text='User Id'),
            preserve_default=False,
        ),
    ]
